### ISSUE TITLE
Won't work with Python 2.7 / 3.4 / 3.5.2 #12

### ISSUE THREAD

**Issue by nixmomo** [Axiacore/cachet-uptime-robot#13]
In #12  i told that the Script won't work and that i should use python 3.5
I updated my python to 3.5.2 and it's still the same... it won't work again.
if i use:

```
root@server2:/home/cachet/cachet-uptime-robot# python3.5 -V 
Python 3.5.2
```

Now i try to use the script

```
root@server2:/home/cachet/cachet-uptime-robot# python3.5 update_status.py config.ini 
root@server2:/home/cachet/cachet-uptime-robot#
```

You see no output and the Metric isn't updated now.

Any new ideas??

**Comment by Aybee2k** [comment]
Same here, no output

What is the [https://url.in.uptime.robot.com] ?

**Comment by camilonova** [comment]
Is the URL you are monitoring with uptime robot.

**Comment by Aybee2k** [comment]
python3 update_status.py config.ini
Updating monitor Webpanel. URL: https://myurl.de. ID: 778314090
Traceback (most recent call last):
  File "/usr/lib64/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib64/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib64/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib64/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update_status.py", line 246, in <module>
    MONITOR.update()
  File "update_status.py", line 215, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 191, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 100, in update_component
    response = request.urlopen(req)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by nixmomo** [comment]
yup somethin changed and the script isn't working again

**Comment by Aybee2k** [comment]
I have not changed anything at the script but only the config.ini as described

**Comment by nixmomo** [comment]
i don't see any issues in my config, the uris and tokens are correct
 :)

**Comment by Aybee2k** [comment]
With me everything is also correct in the config. That script throws however this error with me.

The error happens by the https when I do it with http and the script executes nothing happens.

Ah ich sehe du sprichst auch Deutsch :-)

**Comment by nixmomo** [comment]
Klar ;)

**Comment by Aybee2k** [comment]
Also wenn man das https entfernt aus der Uptimerobot URL habe ich zwar keinen Fehler mehr allerdings wie bei dir oben keine Ausgabe, und bei Cachet wird der Status auch nicht geändert...

**Comment by nixmomo** [comment]
und es wird auch nix an die api übertragen.
Ich hab es mit allen verschiedenen Dingen probiert, verschiedene Python Versionen, verschiedene Betriebssysteme ja selbst Docker Images aber auf keiner Maschine läuft das Script.... Mir gehen langsam die Ideen aus und der Author sagt nur es geht bei Ihm... nur bei keinem anderem ^^

**Comment by Aybee2k** [comment]
Also bei mir funktioniert es ebenfalls nicht. Ich werde das mal Cachet mitteilen vielleicht haben die eine Idee oder nehmen es raus aus deren Webseite bevor noch andere sich damit rumärgern.

Ich selber habe auch einiges versucht nun und alles ohne erfolg.

**Comment by nixmomo** [comment]
sind wir schon zu zweit ;)

**Comment by nixmomo** [comment]
nothing changed... still not working...

**Comment by camilonova** [comment]
It's hard to debug problems like this. For us and many others the script is working fine. I could recommend you to add some print statements to the scripts and find where is not working.

Other than that it would be hard for anyone to help.
