### ISSUE TITLE
HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by androidseb25** [Axiacore/cachet-uptime-robot#16]
Hi,

i actually have the problem that your script response

`Traceback (most recent call last):
  File "update_status.py", line 249, in <module>
    MONITOR.update()
  File "update_status.py", line 218, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 195, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 102, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
`

What can i do for fix everything has worked  few hours before this issue appears.

**Comment by androidseb25** [comment]
Fixed 5 min are to many responses for my server 10min are ok
