### ISSUE TITLE
Error? :(

### ISSUE THREAD

**Issue by niclasreich** [Axiacore/cachet-uptime-robot#19]
```
Updating monitor Domain. URL: https:/domain.com/. ID: 778807132
Traceback (most recent call last):
  File "update_status.py", line 252, in <module>
    MONITOR.update()
  File "update_status.py", line 221, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 197, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 106, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by DefaltNF** [comment]
I have the same here :(

**Comment by 4xx22** [comment]
You need to edit that : http://i.imgur.com/4EMGVKF.png
By the domain on your UptimeRobot ^^
