### ISSUE TITLE
Bad Gateway : Error 502

### ISSUE THREAD

**Issue by Marcel40625** [Axiacore/cachet-uptime-robot#20]
The Script works only from time to time ... most of the time i am getting:

`Traceback (most recent call last):
  File "update_status.py", line 252, in <module>
    MONITOR.update()
  File "update_status.py", line 211, in update
    success, response = uptime_robot.get_monitors(response_times=1)
  File "update_status.py", line 47, in get_monitors
    response = request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
`

but sometimes it works ... any ideas?

this is my config:

`[uptimeRobot]
UptimeRobotMainApiKey = u4XXXXXX-f4XXXXXXXXXXXX98

[oXXXXXXXXXXX.eu]
CachetApiKey = qjWXXXXXXXXXXXXXXXGJ
CachetUrl = http://94.XXX.XXX.59
MetricId = 1
ComponentId = 1

[kimXXXXXXXXX.eu]
CachetApiKey = qjXXXXXXXXXXXXXX4GJ
CachetUrl = http://94.XXX.XXX.59
MetricId = 2
ComponentId = 2`

**Comment by ThomLSA** [comment]
Got the same problem, every single time..

**Comment by Marcel40625** [comment]
it seems the issue is Uptime Robot itself ... not only it checks only every 5 min, you also are not allowed to use the api that much, after i added the cronjob and let it run, it works ...

**Comment by ThomLSA** [comment]
I have more than 5 monitors, this isn't working either.

**Comment by camilonova** [comment]
This has nothing to do with the code base, could be network error or a limit set by uptime robot servers on your IP address. Maybe you are making too many requests.

If anyone has a way to replicate a bug feel free to open a new issue.
