### ISSUE TITLE
ComponentId causes fatal error

### ISSUE THREAD

**Issue by Mecanik** [Axiacore/cachet-uptime-robot#30]
There is a bug with "ComponentId", it returns if set:

```
Traceback (most recent call last):
  File "/root/cachet-uptime-robot-0.1.0/update_status.py", line 250, in <module>
    MONITOR.update()
  File "/root/cachet-uptime-robot-0.1.0/update_status.py", line 219, in update
    self.send_data_to_catchet(monitor)
  File "/root/cachet-uptime-robot-0.1.0/update_status.py", line 196, in send_data_to_catchet
    int(monitor.get('status'))
  File "/root/cachet-uptime-robot-0.1.0/update_status.py", line 102, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 493, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 655, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.4/urllib/request.py", line 602, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 301: Moved Permanently
```

Removing it works, but no data is updated.

`Metric created: {'meta': {'pagination': {'total_pages': 0, 'per_page': 20, 'total': 0, 'current_page': 1, 'links': {'previous_page': None, 'next_page': None}, 'count': 0}}, 'data': []}`

I have multiple components and component groups, unfortunately I do not have time to debug and find the cause.

**Comment by Mecanik** [comment]
I also cloned the project and pulled the latest available, now it will return something different:

```
Traceback (most recent call last):
  File "/root/cachet-uptime-robot/update_status.py", line 252, in <module>
    MONITOR.update()
  File "/root/cachet-uptime-robot/update_status.py", line 221, in update
    self.send_data_to_catchet(monitor)
  File "/root/cachet-uptime-robot/update_status.py", line 197, in send_data_to_catchet
    int(monitor.get('status'))
  File "/root/cachet-uptime-robot/update_status.py", line 106, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by Mecanik** [comment]
Well these things should be stated clearly, and the project should have a latest release even though it's one file...

1. GRAB THE LATEST COMMIT
2. The cachet API Key is found on the cachet page when you click on the avatar icon in the top left (/dashboard/user), it's **NOT the "APP_KEY=SomeRandomString" in the .env file in the cachet web folder**. ( thanks to @nick592prouty https://github.com/Axiacore/cachet-uptime-robot/issues/8 )

Overall disappointed in such poor error checking, such poor information and support for the users.
