### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by sergioloera** [Axiacore/cachet-uptime-robot#36]
Had everything working and today i got an uptime robot email notification expecting cachet to update as well, but nothing. Ran manually and get: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/statusadmin/cachet-uptime-robot/update_status.py", line 275, in update
    self.send_data_to_cachet(monitor)
  File "/home/statusadmin/cachet-uptime-robot/update_status.py", line 228, in send_data_to_cachet
    int(monitor.get('status'))
  File "/home/statusadmin/cachet-uptime-robot/update_status.py", line 102, in update_component
    component = self.get_component(id_component)
  File "/home/statusadmin/cachet-uptime-robot/update_status.py", line 135, in get_component
    return self._request('GET', url)
  File "/home/statusadmin/cachet-uptime-robot/update_status.py", line 201, in _request
    response = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```
Even though i get this, it does get the status in output while running but it looks like it's just not updating cachet.

**Comment by MarcHagen** [comment]
`TimeoutError: [Errno 110] Connection timed out`
With other words, you're status server cannot reach the Cachet endpoint you defined.  
Please double check if this server can reach you're cachet server.

**Comment by sergioloera** [comment]
I have both running on the same server. I was using the FQDN and I guess it didn't like it. Once I changed it to https://127.0.0.1 for the CachetUrl= everything worked.
