### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 301

### ISSUE THREAD

**Issue by RedSpid3r** [Axiacore/cachet-uptime-robot#6]
Getting this error when running the script

```
Traceback (most recent call last):
  File "update_status.py", line 246, in <module>
    MONITOR.update()
  File "update_status.py", line 215, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 191, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 100, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 665, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 612, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 301: Moved Permanently
```

Have verified API key, URL and Component/Metric ID's are correct.

**Comment by RedSpid3r** [comment]
Fixed this, trailing slash on the [UPTIME ROBOT URL] was breaking it

**Comment by bouelcom** [comment]
Where you change that ? i got the same issue ....

**Comment by nick592prouty** [comment]
@bouelcom I think he is talking about in the update_status.py file that shows :

"   self.base_url = 'https://api.uptimerobot.com/'  "needs to be changed to " self.base_url = 'https://api.uptimerobot.com' "

**Comment by camilonova** [comment]
I'm using it with the trailing slash and is working fine. Can you please check again if this is the change that is needed? @bouelcom 

Also please check #8 if solves your issue.

**Comment by nick592prouty** [comment]
I did end up taking the trailing slash from line [105](https://github.com/Axiacore/cachet-uptime-robot/blob/master/update_status.py#L105) and line [125](https://github.com/Axiacore/cachet-uptime-robot/blob/master/update_status.py#L125) . I have pasted the exact update_status.py code I am using successfully. Please excuse the random prints, I use them for debugging, I have it installed under /var/cachet_robot/ , also below is my cron job that is running with no issues. 

*/1 \* \* \* \* python3 /var/cachet_robot/update_status.py /var/cachet_robot/config.ini

```
#!/usr/bin/env python3
import json
import sys
import time
import configparser
from urllib import request
from urllib import parse
from datetime import datetime


class UptimeRobot(object):
    """ Intermediate class for setting uptime stats.
    """
    def __init__(self, api_key):
        self.api_key = api_key
        self.base_url = 'https://api.uptimerobot.com/'

    def get_monitors(self, response_times=0, logs=0, uptime_ratio=30):
        """
        Returns status and response payload for all known monitors.
        """
        url = self.base_url
        url += 'getMonitors?apiKey={0}'.format(self.api_key)
        url += '&noJsonCallback=1&format=json'

        # responseTimes - optional (defines if the response time data of each
        # monitor will be returned. Should be set to 1 for getting them.
        # Default is 0)
        url += '&responseTimes={0}'.format(response_times)

        # logs - optional (defines if the logs of each monitor will be
        # returned. Should be set to 1 for getting the logs. Default is 0)
        url += '&logs={0}'.format(logs)

        # customUptimeRatio - optional (defines the number of days to calculate
        # the uptime ratio(s) for. Ex: customUptimeRatio=7-30-45 to get the
        # uptime ratios for those periods)
        url += '&customUptimeRatio={0}'.format(uptime_ratio)

        # Verifying in the response is jsonp in otherwise is error
        response = request.urlopen(url)
        content = response.read().decode('utf-8')
        j_content = json.loads(content)
        print([j_content])

        if j_content.get('stat'):
            stat = j_content.get('stat')
            if stat == 'ok':
                return True, j_content

        return False, j_content


class CachetHq(object):
    # Uptime Robot status list
    UPTIME_ROBOT_PAUSED = 0
    UPTIME_ROBOT_NOT_CHECKED_YET = 1
    UPTIME_ROBOT_UP = 2
    UPTIME_ROBOT_SEEMS_DOWN = 8
    UPTIME_ROBOT_DOWN = 9

    # Cachet status list
    CACHET_OPERATIONAL = 1
    CACHET_PERFORMANCE_ISSUES = 2
    CACHET_SEEMS_DOWN = 3
    CACHET_DOWN = 4

    def __init__(self, cachet_api_key, cachet_url):
        self.cachet_api_key = cachet_api_key
        self.cachet_url = cachet_url

    def update_component(self, id_component=1, status=None):
        component_status = None

        # Not Checked yet and Up
        if status in [self.UPTIME_ROBOT_NOT_CHECKED_YET, self.UPTIME_ROBOT_UP]:
            component_status = self.CACHET_OPERATIONAL

        # Seems down
        elif status == self.UPTIME_ROBOT_SEEMS_DOWN:
            component_status = self.CACHET_SEEMS_DOWN

        # Down
        elif status == self.UPTIME_ROBOT_DOWN:
            component_status = self.CACHET_DOWN

        if component_status:
            url = '{0}/api/v1/{1}/{2}'.format(
                self.cachet_url,
                'components',
                id_component
            )
            data = parse.urlencode({
                'status': component_status,
            }).encode('utf-8')
            req = request.Request(
                url=url,
                data=data,
                method='PUT',
                headers={'X-Cachet-Token': self.cachet_api_key},
            )
            response = request.urlopen(req)
            content = response.read().decode('utf-8')
            return content

    def set_data_metrics(self, value, timestamp, id_metric=1):
        url = '{0}/api/v1/metrics/{1}/points'.format(
            self.cachet_url,
            id_metric
        )

        data = parse.urlencode({
            'value': value,
            'timestamp': timestamp,
        }).encode('utf-8')
        print({data})
        print("URLLLLLLLLLLLLLLLLLLLL")
        print({url})
        req = request.Request(
            url=url,
            data=data,
            method='POST',
            headers={'X-Cachet-Token': self.cachet_api_key},
        )
        response = request.urlopen(req)

        return json.loads(response.read().decode('utf-8'))

    def get_last_metric_point(self, id_metric):
        url = '{0}/api/v1/metrics/{1}/points'.format(
            self.cachet_url,
            id_metric
        )

        req = request.Request(
            url=url,
            method='GET',
            headers={'X-Cachet-Token': self.cachet_api_key}
        )
        response = request.urlopen(req)
        content = response.read().decode('utf-8')

        last_page = json.loads(
            content
        ).get('meta').get('pagination').get('total_pages')

        url = '{0}/api/v1/metrics/{1}/points?page={2}'.format(
            self.cachet_url,
            id_metric,
            last_page
        )

        req = request.Request(
            url=url,
            method='GET',
            headers={'X-Cachet-Token': self.cachet_api_key},
        )
        response = request.urlopen(req)
        content = response.read().decode('utf-8')

        if json.loads(content).get('data'):
            data = json.loads(content).get('data')[0]
        else:
            data = {
                'created_at': datetime.now().date().strftime(
                    '%Y-%m-%d %H:%M:%S'
                )
            }

        return data


class Monitor(object):
    def __init__(self, monitor_list, api_key):
        self.monitor_list = monitor_list
        self.api_key = api_key

    def send_data_to_catchet(self, monitor):
        """ Posts data to Cachet API.
            Data sent is the value of last `Uptime`.
        """
        try:
            website_config = self.monitor_list[monitor.get('url')]
        except KeyError:
            print('ERROR: monitor is not valid')
            sys.exit(1)

        cachet = CachetHq(
            cachet_api_key=website_config['cachet_api_key'],
            cachet_url=website_config['cachet_url'],
        )

        if 'component_id' in website_config:
            cachet.update_component(
                website_config['component_id'],
                int(monitor.get('status'))
            )

        metric = cachet.set_data_metrics(
            monitor.get('customuptimeratio'),
            int(time.time()),
            website_config['metric_id']
        )
        print('Metric created: {0}'.format(metric))

    def update(self):
        """ Update all monitors uptime and status.
        """
        uptime_robot = UptimeRobot(self.api_key)
        success, response = uptime_robot.get_monitors(response_times=1)
        if success:
            monitors = response.get('monitors').get('monitor')
            for monitor in monitors:
                if monitor['url'] in self.monitor_list:
                    print('Updating monitor {0}. URL: {1}. ID: {2}'.format(
                        monitor['friendlyname'],
                        monitor['url'],
                        monitor['id'],
                    ))
                    self.send_data_to_catchet(monitor)
        else:
            print('ERROR: No data was returned from UptimeMonitor')


if __name__ == "__main__":
    CONFIG = configparser.ConfigParser()
    CONFIG.read(sys.argv[1])
    SECTIONS = CONFIG.sections()

    if not SECTIONS:
        print('ERROR: File path is not valid')
        sys.exit(1)

    UPTIME_ROBOT_API_KEY = None
    MONITOR_DICT = {}
    for element in SECTIONS:
        if element == 'uptimeRobot':
            uptime_robot_api_key = CONFIG[element]['UptimeRobotMainApiKey']
        else:
            MONITOR_DICT[element] = {
                'cachet_api_key': CONFIG[element]['CachetApiKey'],
                'cachet_url': CONFIG[element]['CachetUrl'],
                'metric_id': CONFIG[element]['MetricId'],
            }
            if 'ComponentId' in CONFIG[element]:
                MONITOR_DICT[element].update({
                    'component_id': CONFIG[element]['ComponentId'],
                })

    MONITOR = Monitor(monitor_list=MONITOR_DICT, api_key=uptime_robot_api_key)
    MONITOR.update()
```

**Comment by Mecanik** [comment]
I got the exact same issue with the latest script...
